extern ACTOR actor[];
extern BOMB bomb[];
extern CLOSET closet[];
extern LIFT lift[];
extern STAIRS stairs[];

extern int numstairs;
extern int numclosets;
extern int numlifts;
extern int numbombs;

extern int bombs;
extern ACTOR *speaker;
extern int weapon;
extern int gametime;
extern int showinstr;
extern int showinstrtime;
extern int paused;
extern int score;
extern HISCORE_ENTRY hiscore[];
extern int terrorists;
extern int leaders;
extern int computers;
extern int gameover;
extern int xpos, ypos;
extern char mutesound;
extern int controlscheme;
extern char mouseinitted;
extern unsigned mouseposx;
extern unsigned mouseposy;
extern int mousemovex;
extern int mousemovey;
extern int prevmovex;
extern int prevmovey;
extern int avgmovex;
extern int avgmovey;
extern unsigned mouseb;
extern unsigned prevmouseb;
extern int difficulty;
extern int gamespeed;
extern unsigned char *firebuf;
extern char textbuf[];
extern int ammo[WEAPNUM];
extern const int maxammo[WEAPNUM];
extern const int attackdelaytbl[];
extern int actorradius[];
extern int fistpr[];
extern int pistolpr[];
extern int shotgunpr[];
extern int uzipr[];
extern int flamepr[];
extern int crossbowpr[];
extern int comphealth[];
extern int enemyhealth[];
extern int enemyscore[];
extern int deadenemytype[];
extern int deadenemyitem[];
extern int bnd_hittime;
extern enum bnd_sound bnd_sound;
extern char *gamemsg;
extern int gamemsgtime;
extern int lifecheat;
extern int timecheat;
extern int ammocheat;
extern int speedcheat;
extern int instrcheat;
extern int enemycheat;
extern int grenadecheat;
extern int xshift;
extern int yshift;
extern int trapmsg;
extern int victory;
extern int throwstrength;
extern int fastforward;
extern int liftsound;
extern int scannerdelay;
extern int actors;
extern int kills;
extern int victorybits;
extern int firstdamagedblock;
extern int srminx, srminy, srmaxx, srmaxy;
extern char briefingtext[];
extern char victorytext[];
extern int beginservers;
extern int beginworkstations;

/* Key bindings. */
extern int upkey;
extern int downkey;
extern int leftkey;
extern int rightkey;
extern int strafeleft;
extern int straferight;
extern int strafekey;
extern int walkkey;

extern int attackkey;
extern int nextweap;
extern int prevweap;

extern int pausekey;
extern int linekey;
extern int musickey;
extern int noteskey;

extern int redkey;
extern int greenkey;
extern int bluekey;
extern int yellowkey;

extern int fistkey;
extern int cat5key;
extern int bndkey;
extern int croskey;
extern int pistkey;
extern int shotkey;
extern int uzikey;
extern int grenkey;
extern int bazokey;
extern int scankey;

extern unsigned mouseattack;
extern unsigned mousenextweap;
extern unsigned mouseprevweap;
extern int mousesens;
