name: Build BME and BOFH

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_call:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run the build script
      run: ./build.sh

    - name: Store build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: release-dir
        path: release/
