name: Release BOFH

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    needs: build
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
    - name: Fetch build artifacts
      uses: actions/download-artifact@v3
      with:
        name: release-dir
    - name: Create zip
      uses: TheDoctor0/zip-release@0.7.1
      with:
        type: zip
        filename: bofh-release.zip
        exclusions: '*.git*'

    - name: Create release
      uses: ncipollo/release-action@v1
      with:
        artifacts: bofh-release.zip
